name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    ## Step 1 : Check out the code
    - uses: actions/checkout@v4

    ## Step 2 : Cache dependencies
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    ## Step 3 : Set up Python environment
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    ## Step 4 : Install Dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    ## Step 5 : Debug environment (optional)
    - name: Show Python version
      run: python --version
    - name: Show installed packages
      run: pip freeze
    - name: List project files
      run: ls -R
    
    ## Step 6 : Run Tests
    - name: Test with pytest
      run: |
        pytest -v || true
